### ISSUE TITLE
climate.set_temperature Causes AC to Turn off

### ISSUE THREAD

**Issue by rewse** [KiraPC/ha-switchbot-remote#52]
When I send the following command, my AC is always turned off. 

```
service: climate.set_temperature
target:
  entity_id: climate.dads_room_ac 
data:
  temperature: 26
  hvac_mode: cool
```

According to the log on the mobile app, turning off has been called via API.
The buttons on the mobile app work correctly.

![IMG_1150](https://github.com/user-attachments/assets/5aa0c449-c1d6-45fc-b6f7-4c3944976772)

### Expected Results

- AC is turned on with the new temperature
- AC is altered with new temperature but keeps working

### Actual Results

- AC is turned off

### Frequency

Always

### Version

- Home Assistant 2024.7.2
- SwitchBot Remote IR 1.2.2

**Comment by KiraPC** [comment]
Hello, @rewse 

This is related on how your physical remote works.

Basically, the switchbot hub sends all the command status, if you did not set the "on/off" value before to send the temp, the status will not change.

You have to manually call the service to turn on the device.

Does the Integration Work when you try to turn the device on via the interface?

**Comment by rewse** [comment]
I see. Thank you for your quick reply.

When I send `climate.turn_on` before `climate.set_temperature`, it works as expected.

```
- service: climate.turn_on
  target:
    entity_id: climate.dads_room_ac 
- service: climate.set_temperature
  target:
    entity_id: climate.dads_room_ac 
  data:
    temperature: 26
    hvac_mode: cool
  ```

I can call the above two services at automation without issues, but the Thermostat card cannot choose turning on easily before changing the temperature.

When we call `climate.set_temperature`, could you call SwitchBot API `setAll` with "power state" always on? I think nobody expects turning off when calling `climate.set_temperature`.
