### ISSUE TITLE
Add information from HUB 2 - API 1.1

### ISSUE THREAD

**Issue by goodsale** [KiraPC/ha-switchbot-remote#7]
Via API 1.1 it is possible to query the temperature and humidity of a HUB 2 (new version from Switchbot)

It would be interesting to add Hub 2 with its data to this integration.

As a support I send the instructions via API 1.1 to be sent after authentication to create the sensor which are currently in my configuration.yaml and which work correctly.

Thank you

```
  - resource: https://api.switch-bot.com/v1.1/devices/HUBDEVICEID/status
    scan_interval: 300
    headers:
      Authorization: "{{ states('input_text.switchbot_token') }}"
      sign: "{{ states('sensor.switchbot_sign') }}"
      t: "{{ state_attr('sensor.switchbot_sign','t') }}"
      Content-Type: "application/json"
      nonce: ""
    sensor:
      - name: "SwitchBot Hub 2 Temperature"
        unique_id: switchbot_hub_2_temperature
        value_template: "{{ value_json.body.temperature }}"
        unit_of_measurement: "°C"
        device_class: temperature
      - name: "SwitchBot Hub 2 Humidity"
        unique_id: switchbot_hub_2_humidity
        value_template: "{{ value_json.body.humidity }}"
        unit_of_measurement: "%"
        device_class: humidity
```

**Comment by goodsale** [comment]
With the same logic I noticed that the switchbot  contact_sensor doesn't work properly with the original integration via bluetooth.
I created the sensors that  with API 1.1, updating every 10 seconds
I don't know if this is correct but the created sensor works correctly and provides the open close status correctly.
If it helps, I attach the instructions and these too can be included in the integration

Anyone else having issues with the switchbot contact_sensor open/close states in original integration??

```
  - resource: https://api.switch-bot.com/v1.1/devices/contact_sensor_ID/status
    scan_interval: 10
    headers:
      Authorization: "{{ states('input_text.switchbot_token') }}"
      sign: "{{ states('sensor.switchbot_sign') }}"
      t: "{{ state_attr('sensor.switchbot_sign','t') }}"
      Content-Type: "application/json"
      nonce: ""
    sensor:
      - name: "SwitchBot Finestra Sala Battery"
        unique_id: switchbot_finestra_sala_battery
        value_template: "{{ value_json.body.battery }}"
        unit_of_measurement: "°%"
        device_class: battery
      - name: "SwitchBot Finestra Sala brightness"
        unique_id: switchbot_finestra_sala_brightness
        value_template: "{{ value_json.body.brightness }}"
        device_class: light 
      - name: "SwitchBot Finestra Sala open-close"
        unique_id: switchbot_finestra_sala_oc
        value_template: "{{ value_json.body.openState }}"
        device_class: door       

```
