### ISSUE TITLE
Service media_player.play_media error:

### ISSUE THREAD

**Issue by Teddydm71** [KiraPC/ha-switchbot-remote#80]
Hi, I configured a TV remote control and the number of channels on the switchbot app and it works correctly on the app. I reloaded the integration and I see the media_player.tv entity correctly. As per the documentation I tried to select the channels through the media_player.play_media service. This is the code
```
action: media_player.play_media
data:
     media_content_type: channel
     media_content_id: "3"
target:
     entity_id: media_player.tv
```

This is the error

![Image](https://github.com/user-attachments/assets/aadfb8bd-c40d-4e6f-91a5-ff5bea70ed6c)

![Image](https://github.com/user-attachments/assets/7ed2dc4d-36b4-4d24-8afd-cf69d4f17c11)

Am I doing something wrong?
Thank you
